import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import { ClientWrapper } from "@/components/ClientWrapper";
import { AuthProvider } from "@/components/AuthProvider";
import { Skeleton } from "@/components/ui/skeleton";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          {/*  <AuthProvider>*/}
          <SessionProvider>
            <Suspense fallback={<Skeleton />}>{children}</Suspense>
            {/*</AuthProvider>*/}
          </SessionProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
