import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import React, { Suspense } from "react";
import { ClientWrapper } from "@/components/ClientWrapper";
import { AuthProvider } from "@/components/AuthProvider";
import { Skeleton } from "@/components/ui/skeleton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          <AuthProvider>
            <Suspense fallback={<Skeleton />}>{children}</Suspense>
          </AuthProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
